name: Pool
description: velodrome v2
networks:
  - id: 10
    start_block: 0
    contracts:
      - name: PoolFactory
        handler: src/EventHandlers.ts
        address:
          - 0xF1046053aa5682b4F9a81b5481394DA16BE5FF5a
        events:
          - event: PoolCreated(address indexed token0, address indexed token1, bool indexed stable, address pool, uint256 unnamed)
            requiredEntities:
              - name: LiquidityPool
      - name: Pool
        handler: src/EventHandlers.ts
        address:
          - 0x0493Bf8b6DBB159Ce2Db2E0E8403E753Abd1235b # vAMM-WETH/USDC.e
          - 0x6387765fFA609aB9A1dA1B16C455548Bfed7CbEA # vAMM-WETH/LUSD
        events:
          - event: Fees(address indexed sender, uint256 amount0, uint256 amount1)
            requiredEntities:
              - name: LiquidityPool
          - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
            requiredEntities:
              - name: LiquidityPool
          - event: Sync(uint256 reserve0, uint256 reserve1)
            requiredEntities:
              - name: LiquidityPool
