name: Pool
description: velodrome v2
networks:
  - id: 10
    start_block: 0
    contracts:
      - name: PoolFactory
        handler: src/EventHandlers.ts
        address:
          - 0xF1046053aa5682b4F9a81b5481394DA16BE5FF5a
        events:
          - event: PoolCreated(address indexed token0, address indexed token1, bool indexed stable, address pool, uint256 unnamed)
            requiredEntities:
              - name: StateStore
                labels: ["stateStore"]
      - name: Pool
        handler: src/EventHandlers.ts
        address:
          - 0x0493Bf8b6DBB159Ce2Db2E0E8403E753Abd1235b # vAMM-WETH/USDC.e
          # - 0x6387765fFA609aB9A1dA1B16C455548Bfed7CbEA # vAMM-WETH/LUSD
          - 0xd25711EdfBf747efCE181442Cc1D8F5F8fc8a0D3 # vAMMV2-WETH/OP
          - 0xe9581d0F1A628B038fC8B2a7F5A7d904f0e2f937 # vAMMV2-OP/VELO
          - 0x0df083de449F75691fc5A36477a6f3284C269108 # vAMMV2-OP/USDC
          - 0x8134A2fDC127549480865fB8E5A9E8A8a95a54c5 # vAMMV2-USDC/VELO
          # - 0x7A7f1187c4710010DB17d0a9ad3fcE85e6ecD90a # vAMMV2-RED/VELO
          - 0x58e6433A6903886E440Ddf519eCC573c4046a6b2 # vAMMV2-WETH/VELO
        events:
          - event: Fees(address indexed sender, uint256 amount0, uint256 amount1)
            requiredEntities:
              - name: LiquidityPool
          - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
            requiredEntities:
              - name: StateStore
                labels: ["stateStore"]
              - name: LiquidityPool
          - event: Sync(uint256 reserve0, uint256 reserve1)
            requiredEntities:
              - name: StateStore
                labels: ["stateStore"]
              - name: LiquidityPool
                labels:
                  - singlePool
                arrayLabels:
                  - stablecoinPools
              - name: Token
                arrayLabels:
                  - whitelistedTokens
