name: Pool
description: velodrome v2
networks:
  - id: 10
    start_block: 0
    contracts:
      - name: Pool
        handler: src/EventHandlers.ts
        address:
          - 0x0493Bf8b6DBB159Ce2Db2E0E8403E753Abd1235b
        events:
          - event: Burn(address indexed sender, address indexed to, uint256 amount0, uint256 amount1)
          - event: Mint(address indexed sender, uint256 amount0, uint256 amount1)
          - event: Swap(address indexed sender, address indexed to, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out)
          - event: Sync(uint256 reserve0, uint256 reserve1)
          - event: Transfer(address indexed from, address indexed to, uint256 value)
